### ISSUE TITLE
Zlib succes while miniz_oxide fails

### ISSUE THREAD

**Issue by catenacyber** [rust-lang/flate2-rs#389]
Using code
```
use flate2::read::DeflateDecoder;
use std::io::prelude::*;

fn main() {
    let mut v1 = Vec::new();
    v1.extend_from_slice(&[0xf2, 0x48, 0xcd, 0xc9, 0xc9, 0x07, 0x00]);
    v1.extend_from_slice(&[0, 0, 0xFF, 0xFF]);
    let mut d = DeflateDecoder::new(&v1[..]);
    let mut s = String::new();
    d.read_to_string(&mut s).unwrap();
    println!("{}", s);
}
```

And Cargo.toml
```
[dependencies]
flate2 = { version = "1.0.28", default-features = true }
```

panicks
```
thread 'main' panicked at src/main.rs:10:30:
called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: "corrupt deflate stream" }
```

While Cargo.toml
```
[dependencies]
flate2 = { version = "1.0.28", features = ["zlib"], default-features = false }
```

succeeds in printing Hello

@alexcrichton this example comes from https://datatracker.ietf.org/doc/html/rfc7692#section-7.2.3.1

**Comment by catenacyber** [comment]
One fix may be in `inflate_loop` 

Instead of        
```
if (status as i32) < 0 {
            return Err(MZError::Data);
        }
```

add a check before like
```
        if (status == TINFLStatus::FailedCannotMakeProgress) && orig_in_len == 0 {
            return Err(MZError::Buf);
        }
```

**Comment by Byron** [comment]
Thanks for bringing this up!

To me it seems that rather than making this specific case work by adjusting `inflate_loop`, `miniz_oxide` should be changed to report results similarly to `zlib`.

If you agree, this issue could be closed in favour of a similar one [over at `miniz_oxide`](https://github.com/Frommi/miniz_oxide). Maybe I am missing something though.

**Comment by catenacyber** [comment]
> miniz_oxide should be changed to report results similarly to zlib.

I agree.

> Maybe I am missing something though.

Maybe I am missing something as well (like I should not use a Vec but another structure)

> If you agree, this issue could be closed in favour of a similar one [over at miniz_oxide](https://github.com/Frommi/miniz_oxide).

Did you open one there already ? Or should I (next year) ?

**Comment by Byron** [comment]
> Did you open one there already ? Or should I (next year) ?

I'd be grateful if you would open the issue and manage it whenever you get the chance.
Thanks a lot!

**Comment by catenacyber** [comment]
Closing in favor of https://github.com/Frommi/miniz_oxide/issues/143

**Comment by yuvald-sweet-security** [comment]
Hello,
After this change, how can I tell whether a stream ended due to data truncation? previously I used to check the `Err` output of the read operation, however, now I don't have any way to report that the data is truncated, since `Status::Ok` and `Status::BufError` are treated the same.
Perhaps we can add some indicator for the reason read stopped or some "last error" variable?

**Comment by Byron** [comment]
I'd have trouble to answer this, as it seems to be related to a change in `miniz_oxide` that affects `flate2`. This might be totally wrong as well.
Hence my ping to @oyvindln for a chance to clear this up.
Thank you.

**Comment by yuvald-sweet-security** [comment]
@Byron the change in `miniz_oxide` made truncated streams end with the status `MZError::Buf` instead of `MZError::Data` (as they should). However, that would still be distinguishable. The issue is that `flate2` masks buf errors and returns an `Ok` status, as you can see here:
https://github.com/rust-lang/flate2-rs/blob/98c98c8a57586b37e6f93e94d993e4f038fd8d32/src/zio.rs#L152
If we could have some "last error" field on the stream that lets me know if the read ended due to `Status::BufError` or `Status::StreamEnd` it would be great.

**Comment by oyvindln** [comment]
This would require a separate function or something to retrieve the last status code yeah (don't remember if it's stored somewhere in the internal state or not in either backend.)

A deflate stream is [supposed to mark the last block with the BFINAL header bit set to 1](https://www.rfc-editor.org/rfc/rfc1951#page-9), this is to signal when the data stream actually ends. 

So, a data stream that ends on a block that doesn't have the end block set is technically not a valid stream but it seems it's commonly used anyhow for whatever reason? So I assume that's why the default in flate2 is to accept them? 

It looks like the way the source of original example here works is that the empty flush block that would contain an end block is allowed be skipped to be sent by the way the websocket protocol is designed instead so I guess one way people are then using flate2 is without re-adding it when decompressing and thus missing the end block. (Though that's just from a cursory reading, I'm not at all familiar with websockets so I could be entirely wrong)

But as noted with the current API there is no way of distinguishing between a valid stream with an end block and one that ends on a block that is not marked as an end block.

**Comment by Byron** [comment]
Thanks @yuvald-sweet-security for the details, I think I understand it now. The code-excerpt was also very helpful. Also thanks to @oyvindln for sharing insights.

> So, a data stream that ends on a block that doesn't have the end block set is technically not a valid stream but it seems it's commonly used anyhow for whatever reason? So I assume that's why the default in flate2 is to accept them?

Maybe we could start with a PR that adds a test that indicates the problem.
From there it might be possible to offer some sort of fix or ailment.
